spring.application.name=GymApp

# Database Configuration (Supabase/PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.yyerdahkykhlnkgvyvpm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:zD7W2mVFLxl6rWdM}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Dynamic port for Render para Render
server.port=${PORT:8080}


# Clerk Security Configuration
# Replace with your actual JWKS URL from Clerk Dashboard (API Keys -> Show JWT Public Key -> JWKS URL)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER_URI:https://sensible-dingo-61.clerk.accounts.dev}

# Clerk suele usar esta ruta para las llaves públicas
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URL:https://sensible-dingo-61.clerk.accounts.dev/.well-known/jwks.json}

# Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Security Parameters test
spring.security.user.name=admin
spring.security.user.password=admin123

# jwt test temporality
app.dev.coach-id=user_fantasma_clerk
app.dev.user-id=user_fantasma_clerk2