spring.application.name=GymApp

# Database Configuration (Supabase/PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.yyerdahkykhlnkgvyvpm
spring.datasource.password=zD7W2mVFLxl6rWdM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Clerk Security Configuration
# Replace with your actual JWKS URL from Clerk Dashboard (API Keys -> Show JWT Public Key -> JWKS URL)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://your-clerk-domain.clerk.accounts.dev/.well-known/jwks.json

# Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Security Parameters
spring.security.user.name=admin
spring.security.user.password=admin123